plugins {
    alias libs.plugins.android.application apply false
    alias libs.plugins.android.library apply false
}

tasks.register("clean", Delete) {
    delete(rootProject.layout.buildDirectory)
}

ext {
    // Version name for both library and example-app
    versionName = "1.4.0"
    // Only used for the example app
    exampleAppVersionCode = 11
}