[versions]
# Android 8.0
minSdk = "26"
# Android 17
targetSdk = "37"
compileSdk = "37"

# JDK used by Gradle
java-toolchain = "25"

androidGradlePlugin = "9.3.0"

androidxActivity = "1.13.0"
androidxCamerax = "1.6.1"
androidxFragment = "1.8.9"
androidxLifecycle = "2.11.0"

# https://github.com/google/desugar_jdk_libs/blob/master/CHANGELOG.md
desugar = "2.1.5"

# https://github.com/material-components/material-components-android/releases
material = "1.14.0"

# https://github.com/zxing/zxing
zxingCore = '3.5.4'

[libraries]
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivity" }
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "androidxCamerax" }
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "androidxCamerax" }
androidx-camera-extensions = { group = "androidx.camera", name = "camera-extensions", version.ref = "androidxCamerax" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "androidxCamerax" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "androidxCamerax" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidxFragment" }
androidx-lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }

google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
google-desugar = { group = "com.android.tools", name = "desugar_jdk_libs_nio", version.ref = "desugar" }

zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxingCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }

